function getCart(){return JSON.parse(localStorage.getItem("fashionCart")||"[]")}
function saveCart(c){localStorage.setItem("fashionCart",JSON.stringify(c));updateCartCount()}
function getWishlist(){return JSON.parse(localStorage.getItem("fashionWishlist")||"[]")}
function updateCartCount(){const n=getCart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll(".cart-count").forEach(e=>e.textContent=n)}
function showToast(msg){let t=document.getElementById("toast");if(!t){t=document.createElement("div");t.id="toast";t.className="toast align-items-center text-bg-dark border-0 position-fixed bottom-0 end-0 m-4";t.innerHTML='<div class="d-flex"><div class="toast-body"></div><button class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button></div>';document.body.appendChild(t)}t.querySelector(".toast-body").textContent=msg;new bootstrap.Toast(t,{delay:1800}).show()}
function renderNavbar(active=""){document.getElementById("navbar").innerHTML=`<div class="top-bar"><div class="container d-flex justify-content-between"><span>Free Shipping on Orders Above ₹999</span><span class="d-none d-md-block"><a href="cart.html">Track Order</a><a href="contact.html">Help</a><a href="login.html">Login</a></span></div></div><nav class="navbar navbar-expand-lg sticky-top"><div class="container"><a class="navbar-brand" href="index.html">FashionHub</a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="nav"><ul class="navbar-nav mx-auto"><li class="nav-item"><a class="nav-link ${active==="home"?"active":""}" href="index.html">Home</a></li><li><a class="nav-link" href="shop.html?category=women">Women</a></li><li><a class="nav-link" href="shop.html?category=men">Men</a></li><li><a class="nav-link" href="shop.html?category=kids">Kids</a></li><li><a class="nav-link" href="shop.html?category=shoes">Shoes</a></li><li><a class="nav-link" href="shop.html?category=sale">Sale</a></li></ul><div class="d-flex align-items-center"><a href="shop.html" class="text-dark nav-icon"><i class="bi bi-search"></i></a><a href="login.html" class="text-dark nav-icon"><i class="bi bi-person"></i></a><a href="wishlist.html" class="text-dark nav-icon"><i class="bi bi-heart"></i></a><a href="cart.html" class="text-dark nav-icon"><i class="bi bi-bag"></i><span class="cart-count">0</span></a></div></div></div></nav>`;updateCartCount()}
function renderFooter(){document.getElementById("footer").innerHTML=`<footer><div class="container"><div class="row g-4"><div class="col-md-4"><h5>FashionHub</h5><p>Your destination for modern, stylish and affordable fashion.</p><div class="fs-4"><a class="me-3" href="#">Facebook</a><a class="me-3" href="#">Instagram</a></div></div><div class="col-md-2"><h5>Quick Links</h5><ul><li><a href="index.html">Home</a></li><li><a href="about.html">About Us</a></li><li><a href="shop.html">Shop</a></li><li><a href="contact.html">Contact</a></li></ul></div><div class="col-md-3"><h5>Customer Service</h5><ul><li><a href="cart.html">My Cart</a></li><li><a href="wishlist.html">Wishlist</a></li><li><a href="#">Shipping Policy</a></li><li><a href="#">Return Policy</a></li></ul></div><div class="col-md-3"><h5>Contact</h5><p>Bengaluru, India</p><p>+91 98765 43210</p><p>support@fashionhub.com</p></div></div><div class="copyright">© 2026 FashionHub. All Rights Reserved.</div></div></footer>`}
function productCard(p){return `<div class="col-6 col-md-3"><div class="product-card"><div class="product-image"><span class="sale-badge">${p.sale?"SALE":"NEW"}</span><button class="wishlist-btn" onclick="toggleWishlist(${p.id})"><i class="bi bi-heart"></i></button><a href="product.html?id=${p.id}"><img src="${p.image}" alt="${p.name}"></a></div><div class="product-info"><a href="product.html?id=${p.id}" class="text-dark text-decoration-none"><h5>${p.name}</h5></a><div class="rating">★★★★★</div><span class="fw-bold fs-5">₹${p.price.toLocaleString("en-IN")}</span>${p.oldPrice?`<span class="old-price">₹${p.oldPrice.toLocaleString("en-IN")}</span>`:""}<button class="btn btn-dark btn-sm mt-2 w-100" onclick="addToCart(${p.id})">Add to Cart</button></div></div></div>`}
function renderProducts(id,list){document.getElementById(id).innerHTML=list.length?list.map(productCard).join(""):'<div class="col-12 text-center"><h4>No products found</h4></div>'}
function addToCart(id){let c=getCart(),item=c.find(x=>x.id===id);if(item)item.qty++;else c.push({id,qty:1});saveCart(c);showToast("Product added to cart")}
function removeFromCart(id){saveCart(getCart().filter(x=>x.id!==id));renderCart("cartContent")}
function changeQty(id,d){let c=getCart(),x=c.find(i=>i.id===id);if(x){x.qty+=d;if(x.qty<1)c=c.filter(i=>i.id!==id)}saveCart(c);renderCart("cartContent")}
function toggleWishlist(id){let w=getWishlist();if(w.includes(id)){w=w.filter(x=>x!==id);showToast("Removed from wishlist")}else{w.push(id);showToast("Added to wishlist")}localStorage.setItem("fashionWishlist",JSON.stringify(w))}
function renderWishlist(id){let w=getWishlist(),list=products.filter(p=>w.includes(p.id));renderProducts(id,list)}
function renderCart(id){let c=getCart(),el=document.getElementById(id);if(!c.length){el.innerHTML='<div class="text-center py-5"><i class="bi bi-bag-x fs-1"></i><h3 class="mt-3">Your cart is empty</h3><a href="shop.html" class="btn btn-fashion mt-3">Continue Shopping</a></div>';return}let total=0;el.innerHTML=`<div class="row g-4"><div class="col-lg-8">${c.map(x=>{let p=products.find(a=>a.id===x.id);total+=p.price*x.qty;return `<div class="card mb-3"><div class="card-body d-flex align-items-center gap-3"><img class="cart-img rounded" src="${p.image}"><div class="flex-grow-1"><h5>${p.name}</h5><p class="mb-2">₹${p.price.toLocaleString("en-IN")}</p><div><button class="btn btn-outline-secondary qty-btn" onclick="changeQty(${p.id},-1)">−</button><span class="mx-3">${x.qty}</span><button class="btn btn-outline-secondary qty-btn" onclick="changeQty(${p.id},1)">+</button></div></div><button class="btn btn-outline-danger" onclick="removeFromCart(${p.id})"><i class="bi bi-trash"></i></button></div></div>`}).join("")}</div><div class="col-lg-4"><div class="card"><div class="card-body"><h4>Order Summary</h4><hr><div class="d-flex justify-content-between"><span>Subtotal</span><b>₹${total.toLocaleString("en-IN")}</b></div><div class="d-flex justify-content-between mt-2"><span>Shipping</span><span>${total>=999?"FREE":"₹99"}</span></div><hr><div class="d-flex justify-content-between fs-5"><b>Total</b><b>₹${(total+(total>=999?0:99)).toLocaleString("en-IN")}</b></div><button class="btn btn-fashion w-100 mt-3" onclick="checkout()">Proceed To Checkout</button></div></div></div></div>`}
function checkout(){if(!localStorage.getItem("fashionUser")){alert("Please login before checkout.");location.href="login.html";return}alert("Demo checkout successful!")}
document.addEventListener("DOMContentLoaded",updateCartCount)